export { default as Banner } from "./Banner/Banner";
export { default as CTA } from "./CTA/CTA";
export { default as AboutUs } from "./AboutUs/AboutUs";
export { default as RegularContact } from "./RegularContact/RegularContact";
export { default as OurService } from "./OurService/OurService";
export { default as Technologies } from "./Technologies/Technologies";
export { default as OurWork } from "./Our Work/OurWork";
export { default as PeopleComment } from "./PeopleComment/PeopleComment";
export { default as Dots } from "./Dots/Dots";
export { default as FAQ } from "./FAQ/FAQ";
